
example:
  IEchoService:
    Hello:
      method: "POST"
      path: "/hello"
    Echo:
      method: "POST"
      path: "/echo/:user"
    Since:
      method: "POST"
      path: "/since"
    Stream:
      method: "PUT"
      path: "/stream"
    Redirect:
      method: "GET"
      path: "/redirect"
