
example:
  IEchoService:
    Hello:
      method: "POST"
      path: "/hello"
    Echo:
      method: "POST"
      path: "/echo/:user"
    Since:
      method: "POST"
      path: "/since"
    Stream:
      method: "PUT"
      path: "/stream"
    Redirect:
      method: "GET"
      path: "/redirect"
    Raw:
      method: "POST"
      path: "/raw"
    AdvancedWildcard:
      method: "POST"
      path: "/wildcard/:param_a/static-part/:param_b*/static-part/:param_c/static_part/:param_d*/static_part/:param_e/static_part/:param_f*/static_part"
    BasicWildcard:
      method: "POST"
      path: "/wildcard/:param_a/static-part/:param_b*"
