
example:
  IEchoService:
    Hello:
      method: "POST"
      path: "/hello"
    Echo:
      method: "POST"
      path: "/echo"
    Since:
      method: "POST"
      path: "/since"
    Stream:
      method: "PUT"
      path: "/stream"
